server:
  port: 8000

#api:
#  ribbon:
#    listOfServers:

zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8082 # TODO: url of backend
    client:
      path: /**
      url: http://localhost:8080 # TODO: url of client

