server:
  port: 8000

#api:
#  ribbon:
#    listOfServers:

zuul:
  routes:
    api:
      path: /api/**
      url: https://shanghai-server.herokuapp.com/ # TODO: url of backend
    client:
      path: /**
      url: https://shanghai-client.herokuapp.com/ # TODO: url of client

